--1) 
CREATE PROCEDURE PR_SHOWDETAIL
AS
BEGIN
	SELECT TOP 3 * FROM PERSON AS P 
	INNER JOIN DEPARTMENT D
	ON P.DEPARTMENTID = D.DEPARTMENTID
	LEFT OUTER JOIN  DESIGNATION D1
	ON P.DESIGNATIONID = D1.DESIGNATIONID
END

EXEC PR_SHOWDETAIL 

--2)
CREATE PROCEDURE PR_WORKER_DEPARTMENT
@DEPARTMENTNAME VARCHAR(100)
AS
BEGIN
	SELECT * FROM PERSON AS P
	INNER JOIN DEPARTMENT D
	ON P.DEPARTMENTID = D.DEPARTMENTID
	LEFT OUTER JOIN DESIGNATION D1
	ON P.DESIGNATIONID = D1.DESIGNATIONID
	WHERE @DEPARTMENTNAME = DepartmentName

END

EXEC PR_WORKER_DEPARTMENT 'HR'
EXEC PR_WORKER_DEPARTMENT 'IT'


--3) 
CREATE PROCEDURE PR_WORKERINFO_
@DEPARTMENTNAME VARCHAR(100),
@DESIGNATIONNAME VARCHAR(100)
AS
BEGIN
		SELECT FirstName,Salary,JoiningDate FROM Person AS P
		INNER JOIN Department AS D
		ON P.DepartmentID = D.DepartmentID
		LEFT OUTER JOIN Designation D1
		ON P.DesignationID = D1.DesignationID
		WHERE @DEPARTMENTNAME = DepartmentName OR
			  @DESIGNATIONNAME = DesignationName
END

EXEC PR_WORKERINFO_ 'IT','WELDER'

--4) 
CREATE PROC PR_SHOWDETAIL_FN
@FIRSTNAME VARCHAR(100)
AS
BEGIN
	SELECT P.*,DepartmentName , DesignationName FROM Person AS P
	INNER JOIN Department D
	ON P.DepartmentID = D.DepartmentID
	LEFT OUTER JOIN Designation D1
	ON P.DesignationID = D1.DesignationID
	WHERE @FIRSTNAME = FirstName
END

exec PR_SHOWDETAIL_FN 'hardik'

--5)
CREATE PROC PR_DEPTWISE_SALARY
AS
BEGIN
	SELECT MAX(salary) as max_sal, Min(salary) as min_sal, SUM(salary) as total, DepartmentName from Person as p
	inner join Department d
	on p.DepartmentID = d.DepartmentID
	group by DepartmentName
END

exec PR_DEPTWISE_SALARY
